session_name: bklg
start_directory: ~/acis
windows:
  - window_name: docker
    layout: main-vertical
    panes:
      - shell_command: # pane no. 1
          - docker compose up
        focus: true
      - echo second pane # pane no. 2
  - window_name: dev
    layout: main-vertical
    shell_command_before:
      - cd ~/acis
    panes:
      - shell_command: # pane no. 1
          - nvim .
  - window_name: prod
    layout: main-vertical
    shell_command_before:
      - cd ~/repos/test-data
    panes:
      - shell_command: # pane no. 1
          - vim .
  - window_name: ext
    layout: main-vertical
    shell_command_before:
      - cd ~/repos/bklg-extension
    panes:
      - shell_command: # pane no. 1
          - vim .
  - window_name: playwright
    layout: main-vertical
    shell_command_before:
      - cd ~/repos/playwright
    panes:
      - shell_command: # pane no. 1
          - vim .
  - window_name: bsawf
    layout: main-vertical
    shell_command_before:
      - cd ~/bsawf/bsawf
    panes:
      - shell_command: # pane no. 1
          - vim .
  - window_name: microblog
    layout: main-vertical
    shell_command_before:
      - cd ~/microblog
    panes:
      - shell_command: # pane no. 1
          - vim .
